[tool.ruff]
fix = true

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "S",
    "B",
    "A",
    "COM818",
    "C4",
    "T100",
    "ISC003",
    "G",
    "INP",
    "PIE",
    "T20",
    "RSE",
    "RET",
    "SIM",
    "PTH",
    "TD",
    "ERA001",
    "PL",
    "FLY002",
    "PERF",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF005",
    "RUF010",
    "RUF015",
    "RUF016",
]
ignore = ["E501", "S603", "TD002", "TD003", "PLR0913"]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
line-ending = "lf"
